apiVersion: v1
kind: Pod
metadata:
  generateName: nri-skip-tiny-seq2-
  labels:
    type: interactive
    research-group: rl-team
spec:
  hostIPC: true
  restartPolicy: Never
  containers:
  - name: nri-train
    command: ["python", "-u", "train.py", 
    "--name=nri_skip_tiny_seq2",
    "--epochs=20",
    "--batch_size=2",
    "--hidden_size=32",
    "--node_embedding_dim=32",
#     "--predicted_timesteps=10",
    "--edge_embedding_dim=2", # this is k, i.e. number of edge types
    "--seq_len=2",
    "--skip_connection",
    ]
    # command: ["sleep", "infinity"]
    image: amr-registry.caas.intel.com/aipg/mpettee-pytorch-geometric
    workingDir: /workspace/choreo-graph/
    resources:
      limits:
        nvidia.com/gpu: 0
        cpu: 2
        memory: 300Gi
    volumeMounts:
    - mountPath: "/workspace"
      name: workspace 
    envFrom:
    - configMapRef:
        name: proxy-config
    env:
    - name: LD_LIBRARY_PATH
      value: $LD_LIBRARY_PATH:/.mujoco/mjpro150/bin
    - name: OMP_NUM_THREADS
      value: "1"
  securityContext:
    fsGroup: 17685
    runAsUser: 11964579
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: workdisk

