apiVersion: v1
kind: Pod
metadata:
  generateName: pred10-seq20-cpu-
  labels:
    type: interactive
    research-group: rl-team
spec:
  hostIPC: true
  restartPolicy: Never
  containers:
  - name: nri-train
    command: ["python", "-u", "train.py", 
    "--name=pred10_seq20_cpu",
    "--epochs=50",
    "--batch_size=6",
#     "--batch_limit=10",
#     "--hidden_size=256",
    "--node_embedding_dim=36",
#     "--edge_embedding_dim=2", # this is k, i.e. number of edge types
    "--seq_len=20",
    "--predicted_timesteps=10",
#     "--skip_connection",
    ]
    # command: ["sleep", "infinity"]
    image: amr-registry.caas.intel.com/aipg/mpettee-pytorch-geometric
    workingDir: /workspace/choreo-graph/
    resources:
      limits:
        nvidia.com/gpu: 0
        cpu: 4
        memory: 50Gi
    volumeMounts:
    - mountPath: "/workspace"
      name: workspace 
    envFrom:
    - configMapRef:
        name: proxy-config
    env:
    - name: LD_LIBRARY_PATH
      value: $LD_LIBRARY_PATH:/.mujoco/mjpro150/bin
    - name: OMP_NUM_THREADS
      value: "1"
  securityContext:
    fsGroup: 17685
    runAsUser: 11964579
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: workdisk

